"""
MCP server for gd32f405rg-hmi (product GD32F405RG-HMI-1.0).

GENERATED by mklink_vtfp.codegen -- DO NOT EDIT BY HAND.
Re-run codegen after editing vtfp.yaml.
"""

import os
import sys
from fastmcp import FastMCP

from mklink_vtfp import VTFPAgent, load_project_config

mcp = FastMCP(
    "gd32f405rg-hmi",
    instructions="VTFP v1 controller for GD32F405RG-HMI-1.0. Use these tools to read state, "
                 "send commands, and control the embedded MCU. Commands marked "
                 "requires_arm=True must be preceded by the `arm` tool. "
                 "The arm tool sets a 2-second safety window.",
)

_PROJECT_CONFIG = None  # lazy-loaded

def _agent():
    global _PROJECT_CONFIG
    if _PROJECT_CONFIG is None:
        _PROJECT_CONFIG = load_project_config("vtfp.yaml")
    return VTFPAgent(port=os.environ.get("MKLINK_PORT", "COM5"),
                    config=_PROJECT_CONFIG)


@mcp.tool()
def arm() -> str:
    """ARM the safety protocol. Required before invoking dangerous commands.
    Sets a 2-second window during which dangerous commands may execute."""
    with _agent() as a:
        a.arm()
    return "armed"


@mcp.tool()
def disarm() -> str:
    """Disarm the safety protocol. Cancels any active ARM window."""
    with _agent() as a:
        a.disarm()
    return "disarmed"


@mcp.tool()
def query_info() -> dict:
    """Query the device info (product_id, fw_version, features)."""
    with _agent() as a:
        a.discover()
        info = a.query_info()
        return {
            "product_id": info.product_id,
            "fw_version": info.fw_version,
            "protocol_version": info.protocol_version,
            "features": info.features,
        }


@mcp.tool()
def query_state() -> bytes:
    """Query the 8-byte state word."""
    with _agent() as a:
        a.discover()
        return a.query_state().hex()


@mcp.tool()
def key_press(param: int = 0) -> dict:
    """Inject a key event. param[7:0] = KEY_EVENT_*: 1=UP 2=DOWN 3=ENTER 4=ESC. Routes to menu_navigate()."""
    with _agent() as a:
        a.discover()
        result = a.invoke("KEY_PRESS", param=param)
    return {
        "ok": result.ok,
        "result_code": result.result_code,
        "data_hex": result.data.hex(),
        "elapsed_ms": result.elapsed_ms,
    }


@mcp.tool()
def set_display_mode(param: int = 0) -> dict:
    """Switch LCD test mode. param[7:0] = 0..6 = AUTO/DOTS/LINES/TEXT/UI/NUMERIC/COLORFILL."""
    with _agent() as a:
        a.discover()
        result = a.invoke("SET_DISPLAY_MODE", param=param)
    return {
        "ok": result.ok,
        "result_code": result.result_code,
        "data_hex": result.data.hex(),
        "elapsed_ms": result.elapsed_ms,
    }


@mcp.tool()
def dump_framebuffer(param: int = 0) -> dict:
    """Return 4800 bytes of the 240x160 1bpp LCD framebuffer (raw, packed 3 px/byte via ChangeTab)."""
    with _agent() as a:
        a.discover()
        result = a.invoke("DUMP_FRAMEBUFFER", param=param)
    return {
        "ok": result.ok,
        "result_code": result.result_code,
        "data_hex": result.data.hex(),
        "elapsed_ms": result.elapsed_ms,
    }


@mcp.tool()
def query_state(param: int = 0) -> dict:
    """Return 16 bytes LE: cursor_index(u32) + last_key(u32) + disp_mode(u32) + uptime_ms(u32)."""
    with _agent() as a:
        a.discover()
        result = a.invoke("QUERY_STATE", param=param)
    return {
        "ok": result.ok,
        "result_code": result.result_code,
        "data_hex": result.data.hex(),
        "elapsed_ms": result.elapsed_ms,
    }


if __name__ == "__main__":
    mcp.run()
