"""VTFP v1 codegen — generates MCP server from vtfp.yaml.

Reads a project-level vtfp.yaml configuration and emits:
- generate_mcp_server(): a FastMCP server Python file with one @mcp.tool() per command
- generate_c_dispatch(): a C dispatch source (delegates to vtfp-runtime/codegen/gen_c_dispatch.py)

This is the Python-side counterpart of vtfp-runtime/codegen/gen_c_dispatch.py.
"""

import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List


def _tool_param_type(req_schema: Dict[str, Any]) -> str:
    """Map a dataSchema type to a Python type annotation for the MCP tool."""
    if not req_schema:
        return "int = 0"
    t = req_schema.get("type", "empty")
    if t == "int":
        return "int = 0"
    if t == "uint":
        return "int = 0"
    if t == "string":
        return "str = \"\""
    if t == "bytes":
        return "bytes = b\"\""
    if t == "struct":
        return "dict = None"  # caller passes dict
    return "int = 0"  # default


def _tool_param_name(name: str) -> str:
    """Map a dataSchema field name to a Python kwarg name (snake_case)."""
    return name.lower().replace(" ", "_")


def generate_mcp_server(config: Dict[str, Any], output_path: str) -> str:
    """Generate a FastMCP server Python file from a vtfp.yaml config.

    The output file imports mklink_vtfp.VTFPAgent, instantiates an agent
    with the project config, and registers one @mcp.tool() per command.

    Parameters:
        config: parsed vtfp.yaml dict
        output_path: path to write the generated .py file

    Returns the path to the generated file.
    """
    project_name = config.get("project", {}).get("name", "vtfp-controller")
    product_id   = config.get("project", {}).get("product_id", "VTFP-1.0")
    port         = os.environ.get("MKLINK_PORT", "COM5")
    commands     = config.get("commands", [])

    lines: List[str] = []
    lines.append('"""\n')
    lines.append(f"MCP server for {project_name} (product {product_id}).\n\n")
    lines.append("GENERATED by mklink_vtfp.codegen -- DO NOT EDIT BY HAND.\n")
    lines.append("Re-run codegen after editing vtfp.yaml.\n")
    lines.append('"""\n\n')

    lines.append("import os\n")
    lines.append("import sys\n")
    lines.append("from fastmcp import FastMCP\n\n")
    lines.append("from mklink_vtfp import VTFPAgent, load_project_config\n\n")

    lines.append("mcp = FastMCP(\n")
    lines.append(f'    "{project_name}",\n')
    lines.append(f'    instructions="VTFP v1 controller for {product_id}. Use these tools to read state, "\n')
    lines.append('                 "send commands, and control the embedded MCU. Commands marked "\n')
    lines.append('                 "requires_arm=True must be preceded by the `arm` tool. "\n')
    lines.append('                 "The arm tool sets a 2-second safety window.",\n')
    lines.append(")\n\n")

    lines.append("_PROJECT_CONFIG = None  # lazy-loaded\n\n")
    lines.append("def _agent():\n")
    lines.append("    global _PROJECT_CONFIG\n")
    lines.append('    if _PROJECT_CONFIG is None:\n')
    lines.append('        _PROJECT_CONFIG = load_project_config("vtfp.yaml")\n')
    lines.append('    return VTFPAgent(port=os.environ.get("MKLINK_PORT", "' + port + '"),\n')
    lines.append('                    config=_PROJECT_CONFIG)\n\n\n')

    # Helper for the arm tool
    lines.append('@mcp.tool()\n')
    lines.append("def arm() -> str:\n")
    lines.append('    """ARM the safety protocol. Required before invoking dangerous commands.\n')
    lines.append('    Sets a 2-second window during which dangerous commands may execute."""\n')
    lines.append("    with _agent() as a:\n")
    lines.append("        a.arm()\n")
    lines.append('    return "armed"\n\n\n')

    # Helper for the disarm tool
    lines.append('@mcp.tool()\n')
    lines.append("def disarm() -> str:\n")
    lines.append('    """Disarm the safety protocol. Cancels any active ARM window."""\n')
    lines.append("    with _agent() as a:\n")
    lines.append("        a.disarm()\n")
    lines.append('    return "disarmed"\n\n\n')

    # Helper for query_info (always present, not in config)
    lines.append('@mcp.tool()\n')
    lines.append("def query_info() -> dict:\n")
    lines.append('    """Query the device info (product_id, fw_version, features)."""\n')
    lines.append("    with _agent() as a:\n")
    lines.append("        a.discover()\n")
    lines.append("        info = a.query_info()\n")
    lines.append("        return {\n")
    lines.append('            "product_id": info.product_id,\n')
    lines.append('            "fw_version": info.fw_version,\n')
    lines.append('            "protocol_version": info.protocol_version,\n')
    lines.append('            "features": info.features,\n')
    lines.append("        }\n\n\n")

    lines.append('@mcp.tool()\n')
    lines.append("def query_state() -> bytes:\n")
    lines.append('    """Query the 8-byte state word."""\n')
    lines.append("    with _agent() as a:\n")
    lines.append("        a.discover()\n")
    lines.append("        return a.query_state().hex()\n\n\n")

    # One tool per command in config
    for cmd in commands:
        name = cmd["name"]
        cmd_id = cmd["id"]
        desc = cmd.get("description", f"Invoke {name} (cmd 0x{cmd_id:02X}).")
        requires_arm = cmd.get("requires_arm", False)
        direction = cmd.get("direction", "pc_to_mcu")
        req_schema = cmd.get("request_schema", {"type": "empty"})

        # Tool name: lowercase, e.g. QUERY_INFO -> query_info
        tool_name = name.lower()

        # Build function signature
        sig_parts = []
        # Standard param if request_schema has a single int field
        if req_schema.get("type") in ("int", "uint", "empty"):
            sig_parts.append("param: int = 0")
        elif req_schema.get("type") == "string":
            sig_parts.append("text: str = \"\"")
        elif req_schema.get("type") == "bytes":
            sig_parts.append("data: bytes = b\"\"")
        elif req_schema.get("type") == "struct":
            sig_parts.append("fields: dict = None")
        else:
            sig_parts.append("param: int = 0")

        sig = ", ".join(sig_parts)
        lines.append(f'@mcp.tool()\n')
        lines.append(f'def {tool_name}({sig}) -> dict:\n')
        lines.append(f'    """{desc}"""\n')
        lines.append(f'    with _agent() as a:\n')
        lines.append(f'        a.discover()\n')

        # Build the invoke call
        if req_schema.get("type") == "string":
            lines.append(f'        # Encode string as bytes\n')
            lines.append(f'        data = text.encode("utf-8") if text else b""\n')
            lines.append(f'        result = a.invoke("{name}", data=data)\n')
        elif req_schema.get("type") == "bytes":
            lines.append(f'        result = a.invoke("{name}", data=data)\n')
        elif req_schema.get("type") == "struct":
            lines.append(f'        # Encode struct as a small binary blob (caller responsibility)\n')
            lines.append(f'        import json\n')
            lines.append(f'        data = json.dumps(fields or {{}}).encode("utf-8")\n')
            lines.append(f'        result = a.invoke("{name}", data=data)\n')
        else:
            # int / uint / empty
            lines.append(f'        result = a.invoke("{name}", param=param)\n')

        lines.append(f'    return {{\n')
        lines.append(f'        "ok": result.ok,\n')
        lines.append(f'        "result_code": result.result_code,\n')
        lines.append(f'        "data_hex": result.data.hex(),\n')
        lines.append(f'        "elapsed_ms": result.elapsed_ms,\n')
        lines.append(f'    }}\n\n\n')

    lines.append('if __name__ == "__main__":\n')
    lines.append('    mcp.run()\n')

    Path(output_path).write_text("".join(lines), encoding="utf-8")
    return output_path


def generate_c_dispatch(config: Dict[str, Any], output_path: str) -> str:
    """Generate a C dispatch source from a vtfp.yaml config.

    Delegates to vtfp-runtime/codegen/gen_c_dispatch.py.
    Saves the vtfp.yaml to a temp file and invokes the C-side gen tool.

    Returns the path to the generated C file.
    """
    import tempfile
    import yaml

    # Find vtfp-runtime/codegen/gen_c_dispatch.py relative to this package
    # mklink-vtfp is a sibling of vtfp-runtime in the project
    pkg_root = Path(__file__).resolve().parents[2]  # mklink-vtfp/
    vtfp_runtime_codegen = pkg_root.parent / "vtfp-runtime" / "codegen" / "gen_c_dispatch.py"
    if not vtfp_runtime_codegen.exists():
        raise FileNotFoundError(
            f"vtfp-runtime/codegen/gen_c_dispatch.py not found at {vtfp_runtime_codegen}"
        )

    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as f:
        yaml.safe_dump(config, f)
        yaml_path = f.name
    try:
        subprocess.check_call([sys.executable, str(vtfp_runtime_codegen), yaml_path, output_path])
    finally:
        os.unlink(yaml_path)
    return output_path


# CLI entry point
def main():
    """CLI: usage: python -m mklink_vtfp.codegen <vtfp.yaml> <out_mcp.py> [<out_c_dispatch.c>]"""
    if len(sys.argv) < 3:
        print("Usage: python -m mklink_vtfp.codegen <vtfp.yaml> <out_mcp.py> [<out_c_dispatch.c>]",
              file=sys.stderr)
        sys.exit(1)
    yaml_path = sys.argv[1]
    mcp_out  = sys.argv[2]
    c_out    = sys.argv[3] if len(sys.argv) > 3 else None

    with open(yaml_path) as f:
        import yaml
        config = yaml.safe_load(f)

    generate_mcp_server(config, mcp_out)
    print(f"Generated MCP server: {mcp_out}")
    if c_out:
        generate_c_dispatch(config, c_out)
        print(f"Generated C dispatch: {c_out}")


if __name__ == "__main__":
    main()
