#!/usr/bin/env python3
"""Generate vtfp_user_dispatch.c from a project vtfp.yaml.

Usage:
    python gen_c_dispatch.py <vtfp.yaml> <out.c>

Reads `commands[].id` and `commands[].name` and emits a C source file
with one stub handler per user command, plus a vtfp_user_handlers_init()
function that registers them all.

The generated file is INTENDED to be edited by the user: they replace
each stub with their actual handler implementation.
"""

import sys
import yaml
import textwrap
from pathlib import Path
from datetime import datetime, timezone

DISPATCH_HEADER = """\
/**
 * @file    {filename}
 * @brief   GENERATED by gen_c_dispatch.py — DO NOT EDIT BY HAND
 * @detail  Re-run codegen after editing vtfp.yaml. User may edit
 *          the handler bodies (between the BEGIN/END markers) but
 *          should not change the function signatures.
 *
 * Generated at: {timestamp}
 * Source vtfp.yaml: {source}
 */
#include <vtfp/vtfp.h>
#include <vtfp/vtfp_handlers.h>

/* === BEGIN user handler implementations (editable) === */
"""

DISPATCH_FOOTER = """\
/* === END user handler implementations === */


/**
 * @brief  Register all user-defined handlers. Call from main() after
 *         vtfp_init() and before entering the main loop.
 */
void vtfp_user_handlers_init(void) {
"""

DISPATCH_FOOTER_TAIL = "}\n"


def gen_handler_stub(cmd_id, name, requires_arm, description=""):
    """Generate a stub handler that returns NOT_INIT until the user fills it in."""
    desc = f" /* {description} */" if description else ""
    arm_check = "    (void)req; (void)resp;\n"
    return textwrap.dedent(f"""\
        /**
         * @brief  Handler for {name} (cmd=0x{cmd_id:02X}).{desc}
         * @note   STUB — replace this body with your implementation.
         */
        static int32_t my_{name.lower()}_handler(const vtfp_request_t *req, vtfp_response_t *resp) {{
        {arm_check}    return (int32_t)VTFP_R_NOT_INIT;
        }}
    """)


def gen_registration(cmd_id, name, requires_arm):
    policy = "VTFP_ARM_REQUIRED" if requires_arm else "VTFP_ARM_NONE"
    return f"    vtfp_register_handler(0x{cmd_id:02X}, my_{name.lower()}_handler, {policy});"


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <vtfp.yaml> <out.c>", file=sys.stderr)
        sys.exit(1)
    yaml_path = Path(sys.argv[1])
    out_path  = Path(sys.argv[2])

    with open(yaml_path) as f:
        cfg = yaml.safe_load(f)

    commands = cfg.get("commands", [])
    if not commands:
        print(f"Error: no commands in {yaml_path}", file=sys.stderr)
        sys.exit(1)

    parts = [DISPATCH_HEADER.format(
        filename=out_path.name,
        timestamp=datetime.now(timezone.utc).isoformat(),
        source=yaml_path.name,
    )]

    for cmd in commands:
        parts.append(gen_handler_stub(
            cmd["id"], cmd["name"], cmd.get("requires_arm", False),
            cmd.get("description", ""),
        ))
        parts.append("\n")

    parts.append(DISPATCH_FOOTER)
    for cmd in commands:
        parts.append(gen_registration(cmd["id"], cmd["name"], cmd.get("requires_arm", False)) + "\n")
    parts.append(DISPATCH_FOOTER_TAIL)

    out_path.write_text("".join(parts))
    print(f"Generated {out_path} from {yaml_path} ({len(commands)} commands)")


if __name__ == "__main__":
    main()
