"""Self-test for gen_c_dispatch.py."""

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SAMPLE_YAML = """\
project:
  name: test
  product_id: TEST-1.0
protocol:
  version: "0.1.0"
memory:
  header_base: "0x20000000"
  data_buffer_size: 1024
commands:
  - id: 1
    name: TOGGLE_OUTPUT
    description: Toggle a single digital output bit
    direction: pc_to_mcu
    requires_arm: true
  - id: 2
    name: READ_SENSOR
    direction: pc_to_mcu
    requires_arm: false
"""


def test_codegen_runs():
    yaml_path = HERE / "_test_vtfp.yaml"
    out_path  = HERE / "_test_dispatch.c"
    yaml_path.write_text(SAMPLE_YAML)

    result = subprocess.run(
        [sys.executable, str(HERE / "gen_c_dispatch.py"), str(yaml_path), str(out_path)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, f"codegen failed: {result.stderr}"
    assert out_path.exists()

    content = out_path.read_text()

    # Check both stubs are present
    assert "my_toggle_output_handler" in content
    assert "my_read_sensor_handler" in content

    # Check registrations
    assert "vtfp_register_handler(0x01, my_toggle_output_handler, VTFP_ARM_REQUIRED);" in content
    assert "vtfp_register_handler(0x02, my_read_sensor_handler, VTFP_ARM_NONE);" in content

    # Check markers
    assert "=== BEGIN user handler implementations" in content
    assert "=== END user handler implementations" in content

    # Check generated file is C99-compatible (basic syntax check)
    # Skip this on Windows; rely on the import-and-strip check below
    assert "GENERATED by gen_c_dispatch.py" in content
    assert "DO NOT EDIT BY HAND" in content

    # Cleanup
    yaml_path.unlink()
    out_path.unlink()


def test_codegen_rejects_empty_commands():
    """An empty commands list should fail."""
    import yaml as yamllib
    yaml_path = HERE / "_empty_vtfp.yaml"
    out_path  = HERE / "_empty_dispatch.c"
    yaml_path.write_text(yamllib.dump({
        "project": {"name": "x", "product_id": "X-1.0"},
        "protocol": {"version": "0.1.0"},
        "memory": {"header_base": "0x20000000", "data_buffer_size": 1024},
        "commands": [],
    }))

    result = subprocess.run(
        [sys.executable, str(HERE / "gen_c_dispatch.py"), str(yaml_path), str(out_path)],
        capture_output=True, text=True,
    )
    assert result.returncode != 0
    yaml_path.unlink()
    if out_path.exists():
        out_path.unlink()


if __name__ == "__main__":
    test_codegen_runs()
    test_codegen_rejects_empty_commands()
    print("All codegen tests passed.")
